#!/bin/bash

if [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "0" ]; then
  echo "command exited 0; exiting"
  exit 0
fi

if [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "-1" ]; then
  echo "canceled status code -1 is not considered a failure; exiting"
  exit 0
fi

if [ -z "$BUILDKITE_TOKEN" ]; then
  echo "BUILDKITE_TOKEN not provided; exiting"
  exit 0
fi

if_condition="$BUILDKITE_PLUGIN_BAIL_EARLY_IF"

if [ -n "$if_condition" ]; then
  if [[ "$if_condition" =~ \] ]]; then
    echo "'if' condition cannot contain brackets; exiting"
    exit 1
  fi

  if eval "[ $if_condition ]"; then
    echo "'if' condition evaluated true; continuing"
  else
    echo "'if' condition evaluated false; exiting"
    exit 0
  fi
fi

function add_annotation() {
  local annotation_body="This build was canceled early due to a failure in <a href='https://buildkite.com/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/builds/${BUILDKITE_BUILD_NUMBER}#${BUILDKITE_JOB_ID}'>${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}#${BUILDKITE_BUILD_NUMBER}</a>."
  local build_id="${BUILDKITE_TRIGGERED_FROM_BUILD_ID:-$BUILDKITE_BUILD_ID}"
  local graphql_build_id="$(printf "Build---%s" "$build_id" | base64)"
  local graphql_query="mutation {
    buildAnnotate(input: {buildID: \"$graphql_build_id\", body: \"$annotation_body\", context: "bail-early-plugin", style: ERROR}) {
      annotation {
        uuid
      }
    }
  }"
  # strip newlines and escape quotes so it can be used in a JSON string
  graphql_query="$(echo "$graphql_query" | tr -d '\n' | sed 's/"/\\"/g')"

  curl -s https://graphql.buildkite.com/v1 \
    -X POST \
    -H "Authorization: Bearer $BUILDKITE_TOKEN" \
    -d "{ \"query\": \"$graphql_query\" }"
}

function cancel_build() {
  local org="$BUILDKITE_ORGANIZATION_SLUG"
  local pipeline="${BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG:-$BUILDKITE_PIPELINE_SLUG}"
  local build_number="${BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER:-$BUILDKITE_BUILD_NUMBER}"

  curl -s "https://api.buildkite.com/v2/organizations/${org}/pipelines/${pipeline}/builds/$build_number/cancel" \
    -X PUT \
    -H "Authorization: Bearer $BUILDKITE_TOKEN"
}

buildkite-agent meta-data set bailed-job-id "$BUILDKITE_JOB_ID"

add_annotation
cancel_build
